/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LoginRouteImport } from './login'
import { Route as DashboardRouteImport } from './dashboard'
import { Route as IndexRouteImport } from './index'
import { Route as DashboardWordFinderRouteImport } from './dashboard/word-finder'
import { Route as DashboardSyllableFinderRouteImport } from './dashboard/syllable-finder'
import { Route as DashboardSettingsRouteImport } from './dashboard/settings'
import { Route as DashboardManagementRouteImport } from './dashboard/management'
import { Route as DashboardHomeRouteImport } from './dashboard/home'
import { Route as DashboardChartRouteImport } from './dashboard/chart'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWordFinderRoute = DashboardWordFinderRouteImport.update({
  id: '/word-finder',
  path: '/word-finder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSyllableFinderRoute = DashboardSyllableFinderRouteImport.update({
  id: '/syllable-finder',
  path: '/syllable-finder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardManagementRoute = DashboardManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChartRoute = DashboardChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/chart': typeof DashboardChartRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/syllable-finder': typeof DashboardSyllableFinderRoute
  '/dashboard/word-finder': typeof DashboardWordFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/chart': typeof DashboardChartRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/syllable-finder': typeof DashboardSyllableFinderRoute
  '/dashboard/word-finder': typeof DashboardWordFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/chart': typeof DashboardChartRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/syllable-finder': typeof DashboardSyllableFinderRoute
  '/dashboard/word-finder': typeof DashboardWordFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/chart'
    | '/dashboard/home'
    | '/dashboard/management'
    | '/dashboard/settings'
    | '/dashboard/syllable-finder'
    | '/dashboard/word-finder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/chart'
    | '/dashboard/home'
    | '/dashboard/management'
    | '/dashboard/settings'
    | '/dashboard/syllable-finder'
    | '/dashboard/word-finder'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/chart'
    | '/dashboard/home'
    | '/dashboard/management'
    | '/dashboard/settings'
    | '/dashboard/syllable-finder'
    | '/dashboard/word-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chart': {
      id: '/dashboard/chart'
      path: '/chart'
      fullPath: '/dashboard/chart'
      preLoaderRoute: typeof DashboardChartRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/management': {
      id: '/dashboard/management'
      path: '/management'
      fullPath: '/dashboard/management'
      preLoaderRoute: typeof DashboardManagementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/syllable-finder': {
      id: '/dashboard/syllable-finder'
      path: '/syllable-finder'
      fullPath: '/dashboard/syllable-finder'
      preLoaderRoute: typeof DashboardSyllableFinderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/word-finder': {
      id: '/dashboard/word-finder'
      path: '/word-finder'
      fullPath: '/dashboard/word-finder'
      preLoaderRoute: typeof DashboardWordFinderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/routeTree/gen': {
      id: '/routeTree/gen'
      path: ''
      fullPath: '/routeTree/gen'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardChartRoute: typeof DashboardChartRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardManagementRoute: typeof DashboardManagementRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSyllableFinderRoute: typeof DashboardSyllableFinderRoute
  DashboardWordFinderRoute: typeof DashboardWordFinderRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChartRoute: DashboardChartRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardManagementRoute: DashboardManagementRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSyllableFinderRoute: DashboardSyllableFinderRoute,
  DashboardWordFinderRoute: DashboardWordFinderRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
